# Generated by Django 2.1 on 2021-04-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Boneadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoneUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_ip', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
