# Generated by Django 2.1 on 2021-03-30 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('total_video', models.IntegerField(default=0)),
                ('total_watch', models.IntegerField(default=0)),
                ('added_by_ip', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContentClickMonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=30)),
                ('total_click', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalAdWatchMonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=30)),
                ('total_watch', models.IntegerField(default=0)),
                ('total_click', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalBannerAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=300)),
                ('banner', models.FileField(upload_to='')),
                ('target_link', models.URLField(null=True)),
                ('total_watch', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('added_by_ip', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VerticalAdWatchMonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=30)),
                ('total_watch', models.IntegerField(default=0)),
                ('total_click', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VerticalBannerAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=300)),
                ('banner', models.FileField(upload_to='')),
                ('target_link', models.URLField(null=True)),
                ('total_watch', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('added_by_ip', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=300)),
                ('video', models.FileField(upload_to='')),
                ('total_watch', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('added_by_ip', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAdWatchMonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=30)),
                ('total_watch', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boneadmin.VideoAd')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=600)),
                ('content_link', models.URLField()),
                ('total_watch', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('added_by_ip', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boneadmin.ContentCategory')),
            ],
        ),
        migrations.AddField(
            model_name='verticaladwatchmonthlyreport',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boneadmin.VerticalBannerAd'),
        ),
        migrations.AddField(
            model_name='horizontaladwatchmonthlyreport',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boneadmin.HorizontalBannerAd'),
        ),
        migrations.AddField(
            model_name='contentclickmonthlyreport',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Boneadmin.YoutubeContent'),
        ),
    ]
