# Generated by Django 2.1 on 2021-04-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecontent',
            name='content_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='horizontalbannerad',
            name='banner',
            field=models.FileField(upload_to='HBanner'),
        ),
        migrations.AlterField(
            model_name='verticalbannerad',
            name='banner',
            field=models.FileField(upload_to='VBanner'),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='video',
            field=models.FileField(upload_to='VideoAD'),
        ),
    ]
