# Generated by Django 2.1 on 2021-03-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcategory',
            old_name='total_watch',
            new_name='total_click',
        ),
        migrations.RenameField(
            model_name='youtubecontent',
            old_name='total_watch',
            new_name='total_click',
        ),
    ]
