# Generated by Django 2.1 on 2021-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecontent',
            name='content_poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
