# Generated by Django 2.1 on 2021-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0002_youtubecontent_content_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecontent',
            name='content_poster',
            field=models.ImageField(blank=True, upload_to='Poster'),
        ),
    ]
