# Generated by Django 2.1 on 2021-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0002_auto_20210417_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecontent',
            name='content_description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='youtubecontent',
            name='content_link',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
