# Generated by Django 2.1 on 2021-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0003_auto_20210420_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentclickmonthlyreport',
            name='total_watch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horizontalbannerad',
            name='total_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verticalbannerad',
            name='total_click',
            field=models.IntegerField(default=0),
        ),
    ]
