# Generated by Django 2.1 on 2021-04-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boneadmin', '0006_auto_20210412_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
